// controllers/assignmentController.js - DESCRIPTIVE ONLY
const Assignment = require('../models/Assignment');
const Submission = require('../models/Submission');
const Course = require('../models/Course');
const geminiService = require('../services/geminiService');
const path = require('path');
const fs = require('fs');
const PDFDocument = require('pdfkit');

class AssignmentController {
    // ✅ GENERATE ONLY DESCRIPTIVE ASSIGNMENTS
    async generateAssignmentFromCustomPrompt(req, res) {
        try {
            const { courseId } = req.params;
            const {
                customPrompt,
                title,
                dueDate,
                numQuestions = 5  // Default 5, max 5
            } = req.body;

            // Validate
            if (!customPrompt || !customPrompt.trim()) {
                return res.status(400).json({
                    success: false,
                    message: 'Custom prompt is required'
                });
            }

            const course = await Course.findById(courseId);
            if (!course) {
                return res.status(404).json({
                    success: false,
                    message: 'Course not found'
                });
            }

            // ✅ FORCE DESCRIPTIVE TYPE - No MCQs, No Mixed
            const type = 'descriptive';
            
            // ✅ ENFORCE MAX 5 QUESTIONS
            const questionsToGenerate = Math.min(numQuestions, 5);
            
            console.log(`📝 Request: ${questionsToGenerate} descriptive questions`);

            // Call gemini
            const result = await geminiService.generateAssignmentContent(
                customPrompt, 
                type, 
                questionsToGenerate
            );

            if (!result.success) {
                return res.status(500).json({
                    success: false,
                    message: 'Failed to generate assignment',
                    error: result.error
                });
            }

            // Create assignment
            const assignment = new Assignment({
                courseId,
                title: title || `Assignment - ${course.name}`,
                questions: [result.content],
                dueDate: dueDate ? new Date(dueDate) : new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
                generatedByAI: true,
                type: 'descriptive', // ✅ Always descriptive
                numQuestions: questionsToGenerate,
                promptUsed: customPrompt,
                autoGenerated: true
            });

            await assignment.save();

            // ✅ Add to course
            if (!course.assignments) {
                course.assignments = [];
            }
            course.assignments.push(assignment._id);
            await course.save();
            
            console.log(`✅ Assignment ${assignment._id} added to course`);

            // Generate PDF
            const pdfPath = await this.generateAssignmentPDF(assignment, result.content);
            console.log(`📄 PDF Path: ${pdfPath}`);

            // Update assignment with PDF path
            assignment.assignmentPdfPath = pdfPath;
            assignment.pdfUrl = `http://localhost:5000${pdfPath}`;
            await assignment.save();

            // Verify file exists
            const fullPath = path.join(__dirname, '..', 'public', pdfPath);
            console.log(`📁 File exists: ${fs.existsSync(fullPath)}`);

            res.json({
                success: true,
                message: 'Descriptive assignment generated',
                assignment: {
                    _id: assignment._id,
                    title: assignment.title,
                    courseId: assignment.courseId,
                    type: assignment.type,
                    numQuestions: assignment.numQuestions,
                    dueDate: assignment.dueDate,
                    generatedByAI: assignment.generatedByAI,
                    assignmentPdfPath: assignment.assignmentPdfPath,
                    pdfUrl: assignment.pdfUrl,
                    preview: assignment.questions[0].substring(0, 500) + '...'
                }
            });

        } catch (error) {
            console.error('❌ Error:', error);
            res.status(500).json({
                success: false,
                message: 'Server error'
            });
        }
    }

    // ✅ GENERATE PDF FOR DESCRIPTIVE ASSIGNMENT
    async generateAssignmentPDF(assignment, content) {
        return new Promise((resolve, reject) => {
            try {
                const uploadsDir = path.join(__dirname, '..', 'public', 'uploads', 'assignments');
                
                console.log(`📁 Creating directory: ${uploadsDir}`);
                
                if (!fs.existsSync(uploadsDir)) {
                    fs.mkdirSync(uploadsDir, { recursive: true });
                    console.log(`✅ Directory created: ${uploadsDir}`);
                }

                const timestamp = Date.now();
                const fileName = `assignment_${assignment._id}_${timestamp}.pdf`;
                const filePath = path.join(uploadsDir, fileName);
                const publicPath = `/uploads/assignments/${fileName}`;

                console.log(`📄 Creating PDF at: ${filePath}`);

                const doc = new PDFDocument({ margin: 50 });
                const stream = fs.createWriteStream(filePath);
                
                doc.pipe(stream);

                // Header
                doc.fontSize(20).text(assignment.title || 'Assignment', { align: 'center' });
                doc.moveDown();
                
                // Info
                doc.fontSize(12).text(`Course ID: ${assignment.courseId}`);
                doc.text(`Generated: ${new Date().toLocaleDateString()}`);
                doc.text(`Due Date: ${assignment.dueDate ? assignment.dueDate.toLocaleDateString() : 'Not set'}`);
                doc.text(`Questions: ${assignment.numQuestions || '5'}`);
                doc.text(`Type: DESCRIPTIVE`);
                doc.moveDown();
                doc.text('-'.repeat(50));
                doc.moveDown();

                // Content
                doc.fontSize(14).text('DESCRIPTIVE QUESTIONS:', { underline: true });
                doc.moveDown();
                
                // Clean content for PDF
                let cleanContent = content || 'Assignment content will appear here.';
                cleanContent = cleanContent.replace(/\*\*/g, '').replace(/```/g, '');
                
                doc.fontSize(12).text(cleanContent);

                // Footer
                doc.moveDown(2);
                doc.fontSize(10).text('-'.repeat(50), { align: 'center' });
                doc.text('Generated by Assignment System', { align: 'center' });

                doc.end();

                stream.on('finish', () => {
                    console.log(`✅ PDF created: ${publicPath}`);
                    
                    if (fs.existsSync(filePath)) {
                        const stats = fs.statSync(filePath);
                        console.log(`📊 File size: ${stats.size} bytes`);
                        resolve(publicPath);
                    } else {
                        reject(new Error('PDF file was not created'));
                    }
                });

                stream.on('error', (error) => {
                    console.error('❌ PDF stream error:', error);
                    reject(error);
                });

            } catch (error) {
                console.error('❌ PDF generation error:', error);
                reject(error);
            }
        });
    }

    // ✅ GET ASSIGNMENT DETAILS (SAME)
    async getAssignment(req, res) {
        try {
            const { assignmentId } = req.params;

            const assignment = await Assignment.findById(assignmentId)
                .populate('courseId', 'name');

            if (!assignment) {
                return res.status(404).json({
                    success: false,
                    message: 'Assignment not found'
                });
            }

            // Add PDF URL if not present
            let pdfUrl = assignment.pdfUrl;
            if (!pdfUrl && assignment.assignmentPdfPath) {
                pdfUrl = `http://localhost:5000${assignment.assignmentPdfPath}`;
            }

            // Check if student has submitted
            let studentSubmission = null;
            if (req.user.role === 'student') {
                studentSubmission = await Submission.findOne({
                    assignmentId,
                    studentId: req.user.id
                });
            }

            const assignmentResponse = {
                _id: assignment._id,
                title: assignment.title,
                courseId: assignment.courseId._id,
                courseName: assignment.courseId.name,
                questions: assignment.questions,
                dueDate: assignment.dueDate,
                type: assignment.type,
                numQuestions: assignment.numQuestions,
                generatedByAI: assignment.generatedByAI,
                assignmentPdfPath: assignment.assignmentPdfPath,
                pdfUrl: pdfUrl,
                createdAt: assignment.createdAt,
                studentSubmission: studentSubmission ? {
                    _id: studentSubmission._id,
                    submittedAt: studentSubmission.submittedAt,
                    evaluated: studentSubmission.evaluated,
                    score: studentSubmission.evaluation?.score,
                    feedback: studentSubmission.evaluation?.feedback
                } : null
            };

            res.json({
                success: true,
                assignment: assignmentResponse
            });

        } catch (error) {
            console.error('Get assignment error:', error);
            res.status(500).json({
                success: false,
                message: 'Failed to get assignment'
            });
        }
    }

    // ✅ GET COURSE ASSIGNMENTS (SAME)
    async getCourseAssignments(req, res) {
        try {
            const { courseId } = req.params;

            // First check if course exists
            const course = await Course.findById(courseId);
            if (!course) {
                return res.status(404).json({
                    success: false,
                    message: 'Course not found'
                });
            }

            console.log(`📚 Fetching assignments for course: ${courseId}`);

            // Find assignments for this course
            const assignments = await Assignment.find({ courseId })
                .sort({ dueDate: 1 });

            console.log(`📊 Found ${assignments.length} assignments`);

            // Add PDF URLs
            const assignmentsWithPdf = assignments.map(assignment => {
                const assignmentObj = assignment.toObject();
                
                // Set PDF URL
                if (assignmentObj.assignmentPdfPath) {
                    let pdfPath = assignmentObj.assignmentPdfPath;
                    if (!pdfPath.startsWith('/uploads/') && !pdfPath.startsWith('http')) {
                        pdfPath = `/uploads/assignments/${pdfPath}`;
                    }
                    
                    assignmentObj.pdfUrl = `http://localhost:5000${pdfPath}`;
                    assignmentObj.downloadUrl = `http://localhost:5000${pdfPath}`;
                }
                // Fallback
                else if (assignmentObj.pdfUrl) {
                    assignmentObj.downloadUrl = assignmentObj.pdfUrl;
                }
                // Last resort
                else {
                    assignmentObj.pdfUrl = `http://localhost:5000/api/assignments/${assignment._id}/pdf`;
                    assignmentObj.downloadUrl = assignmentObj.pdfUrl;
                }
                
                return assignmentObj;
            });

            // For students, add submission status
            if (req.user.role === 'student') {
                const submissions = await Submission.find({
                    assignmentId: { $in: assignments.map(a => a._id) },
                    studentId: req.user.id
                });

                assignmentsWithPdf.forEach(assignment => {
                    const submission = submissions.find(s => 
                        s.assignmentId.toString() === assignment._id.toString()
                    );
                    
                    assignment.submitted = !!submission;
                    assignment.submissionId = submission?._id;
                    assignment.evaluated = submission?.evaluated;
                    assignment.score = submission?.evaluation?.score;
                    assignment.feedback = submission?.evaluation?.feedback;
                    
                    // Calculate status
                    const now = new Date();
                    assignment.status = assignment.submitted ? 
                        'submitted' : 
                        (new Date(assignment.dueDate) < now ? 'overdue' : 'pending');
                });
            }

            res.json({
                success: true,
                assignments: assignmentsWithPdf,
                count: assignmentsWithPdf.length
            });

        } catch (error) {
            console.error('❌ Get course assignments error:', error);
            res.status(500).json({
                success: false,
                message: 'Failed to get assignments'
            });
        }
    }

    // ✅ VIEW PDF (SAME)
    async viewAssignmentPDF(req, res) {
        try {
            const { assignmentId } = req.params;
            
            console.log(`📄 Requesting PDF for assignment: ${assignmentId}`);
            
            const assignment = await Assignment.findById(assignmentId);
            
            if (!assignment) {
                return res.status(404).json({
                    success: false,
                    message: 'Assignment not found'
                });
            }

            // Check if PDF exists
            if (assignment.assignmentPdfPath) {
                const filePath = path.join(__dirname, '..', 'public', assignment.assignmentPdfPath);
                
                console.log(`🔍 Looking for PDF at: ${filePath}`);
                
                if (fs.existsSync(filePath)) {
                    console.log(`✅ PDF found, sending to client`);
                    
                    if (req.query.download === 'true') {
                        res.download(filePath, `assignment-${assignmentId}.pdf`);
                    } else {
                        res.sendFile(filePath);
                    }
                } else {
                    console.log(`❌ PDF not found at path, generating on the fly`);
                    // Generate PDF on the fly
                    await this.generateAndSendPDF(res, assignment);
                }
            } else {
                console.log(`📝 No PDF path, generating on the fly`);
                // Generate PDF on the fly
                await this.generateAndSendPDF(res, assignment);
            }
            
        } catch (error) {
            console.error('❌ PDF view error:', error);
            res.status(500).json({
                success: false,
                message: 'Failed to get PDF'
            });
        }
    }

    // ✅ HELPER: GENERATE AND SEND PDF
    async generateAndSendPDF(res, assignment) {
        return new Promise((resolve) => {
            res.setHeader('Content-Type', 'application/pdf');
            res.setHeader('Content-Disposition', `inline; filename="assignment-${assignment._id}.pdf"`);
            
            const doc = new PDFDocument();
            doc.pipe(res);
            
            doc.fontSize(20).text(assignment.title || 'Assignment', { align: 'center' });
            doc.moveDown();
            
            doc.fontSize(12).text(`Course ID: ${assignment.courseId}`);
            doc.text(`Generated: ${new Date().toLocaleDateString()}`);
            doc.text(`Due Date: ${assignment.dueDate ? assignment.dueDate.toLocaleDateString() : 'Not set'}`);
            doc.moveDown();
            
            if (assignment.questions && assignment.questions.length > 0) {
                doc.fontSize(14).text('QUESTIONS:', { underline: true });
                doc.moveDown();
                doc.fontSize(12).text(assignment.questions[0]);
            } else {
                doc.text('No questions available');
            }
            
            doc.end();
            
            doc.on('end', () => {
                resolve();
            });
        });
    }

    // ✅ EVALUATE SUBMISSION (SAME)
    // assignmentController.js - evaluateSubmission function
async evaluateSubmission(req, res) {
    try {
        console.log(`📊 Evaluating submission: ${submissionId}`);
        
        // Get submission and assignment
        const submission = await Submission.findById(submissionId);
        const assignment = await Assignment.findById(submission.assignmentId);
        
        console.log(`📝 Assignment questions: ${assignment.questions[0].substring(0, 200)}...`);
        
        // Get student answer text
        let studentAnswerText = '';
        if (submission.textAnswer) {
            studentAnswerText = submission.textAnswer;
            console.log(`📝 Text answer length: ${studentAnswerText.length}`);
        } else if (submission.pdfPath) {
            const pdfPath = path.join(__dirname, '..', 'public', submission.pdfPath);
            studentAnswerText = await geminiService.extractTextFromPDFFile(pdfPath);
            console.log(`📝 PDF extracted length: ${studentAnswerText.length}`);
        }
        
        console.log('🤖 Calling Gemini for evaluation...');
        
        // Call Gemini
        const evaluationResult = await geminiService.evaluateSubmission(
            assignment.questions.join('\n'),
            studentAnswerText
        );
        
        console.log(`✅ Evaluation result:`, evaluationResult);
        
        if (evaluationResult.success) {
            // Update submission
            submission.evaluated = true;
            submission.evaluation = {
                score: evaluationResult.evaluation.score,
                feedback: evaluationResult.evaluation.feedback || "Evaluated by AI",
                evaluatedAt: new Date(),
                aiGenerated: true,
                detailedEvaluation: evaluationResult.evaluation
            };
            
            await submission.save();
            
            console.log(`🎯 Final score: ${evaluationResult.evaluation.score}/100`);
            
            return res.json({
                success: true,
                message: 'Evaluation completed',
                evaluation: submission.evaluation
            });
        }
        
    } catch (error) {
        console.error('❌ Evaluation error:', error);
        return res.status(500).json({
            success: false,
            message: 'Evaluation failed',
            error: error.message
        });
    }
}

    // ✅ AUTO-EVALUATE ON SUBMISSION (SAME)
    async autoEvaluateSubmission(submissionId) {
        try {
            const submission = await Submission.findById(submissionId)
                .populate('assignmentId');
            
            if (!submission || submission.evaluated) {
                return;
            }
            
            console.log(`🤖 Auto-evaluating submission: ${submissionId}`);
            
            // Extract text from submitted PDF
            const studentAnswerText = await geminiService.extractTextFromPDFFile(
                path.join(__dirname, '..', 'public', submission.pdfPath)
            );
            
            // Get assignment
            const assignment = await Assignment.findById(submission.assignmentId);
            
            // Evaluate
            const evaluationResult = await geminiService.evaluateSubmission(
                assignment.questions.join('\n'),
                studentAnswerText
            );
            
            if (evaluationResult.success) {
                submission.evaluated = true;
                submission.evaluation = {
                    score: evaluationResult.evaluation.score,
                    feedback: evaluationResult.evaluation.feedback || "Auto-evaluated by AI",
                    evaluatedAt: new Date(),
                    aiGenerated: true
                };
                
                await submission.save();
                console.log(`✅ Auto-evaluation complete. Score: ${evaluationResult.evaluation.score}/100`);
            }
            
        } catch (error) {
            console.error('Auto-evaluation error:', error);
        }
    }

    // ✅ GET ALL SUBMISSIONS (SAME)
    async getAssignmentSubmissions(req, res) {
        try {
            const { assignmentId } = req.params;
            
            const submissions = await Submission.find({ assignmentId })
                .populate('studentId', 'name email')
                .sort({ submittedAt: -1 });
            
            // Add full PDF URLs
            const submissionsWithUrls = submissions.map(sub => {
                const subObj = sub.toObject();
                if (sub.pdfPath) {
                    subObj.fullPdfUrl = `http://localhost:5000${sub.pdfPath}`;
                }
                return subObj;
            });

            res.json({
                success: true,
                submissions: submissionsWithUrls,
                count: submissions.length
            });
            
        } catch ( error) {
            console.error('Get submissions error:', error);
            res.status(500).json({
                success: false,
                message: 'Failed to get submissions'
            });
        }
    }

    // ✅ AUTO-GENERATE FOR NEW COURSE - DESCRIPTIVE ONLY
    async generateAssignmentForNewCourse(courseId, resources, assignmentData) {
        try {
            console.log(`🤖 Auto-generating descriptive assignment for course: ${courseId}`);
            
            const course = await Course.findById(courseId);
            if (!course) {
                console.error('Course not found:', courseId);
                return;
            }
            
            // Extract PDF content from resources
            let pdfContent = '';
            
            for (const resource of resources) {
                if (resource.type === 'pdf' && resource.url) {
                    try {
                        const pdfPath = path.join(__dirname, '..', 'public', resource.url);
                        if (fs.existsSync(pdfPath)) {
                            const text = await geminiService.extractTextFromPDFFile(pdfPath);
                            pdfContent += text.substring(0, 1000) + '\n\n';
                        }
                    } catch (err) {
                        console.log('PDF extraction error:', err.message);
                    }
                }
            }
            
            // Use course description if no PDF content
            const prompt = pdfContent 
                ? `Create descriptive assignment from these notes: ${pdfContent.substring(0, 1500)}`
                : `Create descriptive assignment about: ${course.name} - ${course.description.substring(0, 500)}`;
            
            // ✅ ALWAYS DESCRIPTIVE, MAX 5 QUESTIONS
            const numQuestions = Math.min(assignmentData.numQuestions || 5, 5);
            
            const result = await geminiService.generateAssignmentContent(
                prompt,
                'descriptive', // ✅ Always descriptive
                numQuestions
            );
            
            if (!result.success) {
                console.error('AI generation failed:', result.error);
                throw new Error('AI generation failed');
            }
            
            // Create assignment
            const assignment = new Assignment({
                courseId,
                title: assignmentData.title || `Assignment - ${course.name}`,
                questions: [result.content],
                dueDate: assignmentData.dueDate || new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
                generatedByAI: true,
                type: 'descriptive', // ✅ Always descriptive
                numQuestions: numQuestions,
                promptUsed: prompt.substring(0, 500),
                autoGenerated: true
            });
            
            await assignment.save();
            
            // Generate PDF
            const pdfPath = await this.generateAssignmentPDF(assignment, result.content);
            assignment.assignmentPdfPath = pdfPath;
            assignment.pdfUrl = `http://localhost:5000${pdfPath}`;
            await assignment.save();
            
            // Add to course
            course.assignments = course.assignments || [];
            course.assignments.push(assignment._id);
            await course.save();
            
            console.log(`✅ Auto-generated descriptive assignment: ${assignment._id}`);
            return assignment;
            
        } catch (error) {
            console.error('Auto-assignment generation error:', error);
            throw error;
        }
    }
}

// Create instance
const assignmentController = new AssignmentController();

// Export
module.exports = {
    assignmentController,
    generateAssignmentForNewCourse: assignmentController.generateAssignmentForNewCourse.bind(assignmentController)
};