// models/Assignment.js - Complete with all required fields
const mongoose = require('mongoose');

const assignmentSchema = new mongoose.Schema({
    courseId: { 
        type: mongoose.Schema.Types.ObjectId, 
        ref: 'Course', 
        required: true 
    },
    title: { 
        type: String, 
        required: true 
    },
    questions: [{ 
        type: String 
    }],
    dueDate: { 
        type: Date, 
        required: true 
    },
    generatedByAI: { 
        type: Boolean, 
        default: false 
    },
    promptUsed: { 
        type: String 
    },
    type: { 
        type: String, 
        enum: ['mcq', 'descriptive', 'mixed'], 
        default: 'mixed' 
    },
    numQuestions: { 
        type: Number, 
        default: 5 
    },
    assignmentPdfPath: { 
        type: String 
    },
    autoGenerated: { 
        type: Boolean, 
        default: false 
    },
    submissions: [{ 
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Submission'
    }],
    createdAt: { 
        type: Date, 
        default: Date.now 
    },
    updatedAt: { 
        type: Date, 
        default: Date.now 
    }
});

// Indexes for performance
assignmentSchema.index({ courseId: 1 });
assignmentSchema.index({ dueDate: 1 });
assignmentSchema.index({ generatedByAI: 1 });
assignmentSchema.index({ createdAt: -1 });
assignmentSchema.index({ courseId: 1, dueDate: 1 });

// Update timestamp on save
assignmentSchema.pre('save', function(next) {
    this.updatedAt = Date.now();
    next();
});

module.exports = mongoose.model('Assignment', assignmentSchema);