// models/Assignment.js - UPDATED (ONLY DESCRIPTIVE)
const mongoose = require('mongoose');

const assignmentSchema = new mongoose.Schema({
    courseId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Course',
        required: true
    },
    title: {
        type: String,
        required: true,
        trim: true
    },
    questions: [{
        type: String,
        required: true
    }],
    dueDate: {
        type: Date,
        required: true
    },
    type: {
        type: String,
        enum: ['descriptive'], // ✅ ONLY DESCRIPTIVE
        default: 'descriptive'
    },
    numQuestions: {
        type: Number,
        default: 5,
        max: 5 // ✅ MAX 5 QUESTIONS
    },
    generatedByAI: {
        type: Boolean,
        default: false
    },
    autoGenerated: {
        type: Boolean,
        default: false
    },
    promptUsed: {
        type: String,
        default: ''
    },
    assignmentPdfPath: {
        type: String,
        default: ''
    },
    pdfUrl: {
        type: String,
        default: ''
    },
    isActive: {
        type: Boolean,
        default: true
    },
    createdBy: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User'
    },
    createdAt: {
        type: Date,
        default: Date.now
    },
    updatedAt: {
        type: Date,
        default: Date.now
    }
});

// Update timestamp on save
assignmentSchema.pre('save', function(next) {
    this.updatedAt = Date.now();
    next();
});

const Assignment = mongoose.model('Assignment', assignmentSchema);

module.exports = Assignment;